https://codeforces.com/blog/entry/7383
https://codeforces.com/blog/entry/64236
https://codeforces.com/blog/entry/20032
https://codeforces.com/blog/entry/61203
https://codeforces.com/blog/entry/22284
https://codeforces.com/blog/entry/68271
https://codeforces.com/blog/entry/22284
https://codeforces.com/blog/entry/44711
https://codeforces.com/blog/entry/65037
https://codeforces.com/blog/entry/50353
https://codeforces.com/blog/entry/63328
https://codeforces.com/topic/64641/en1
https://codeforces.com/blog/entry/58197
https://codeforces.com/blog/entry/55574
https://cp-algorithms.com/data_structures/sqrt_decomposition.html
https://www.geeksforgeeks.org/mos-algorithm-query-square-root-decomposition-set-1-introduction/
https://www.hackerearth.com/practice/notes/mos-algorithm/
https://www.hackerearth.com/ru/practice/notes/mos-algorithm-query-square-root-decomposition/
https://www.commonlounge.com/discussion/6205343265434ffc88723f70fec0b796
https://discuss.codechef.com/t/query-regarding-mos-algorithm/17607
https://stackoverflow.com/questions/36405620/mos-algorithm-to-compute-power-of-array
http://cfrp.azurewebsites.net/blog/entry/63995
http://hmrockstar.blogspot.com/2017/07/mos-query-sqrt-decomposition-algorithm.html
http://hmrockstar.blogspot.com/
http://codewarriers.blogspot.com/
https://codeforces.com/blog/entry/43230
https://codeforces.com/blog/entry/46399?#comment-308528
https://codeforces.com/blog/entry/57955
https://codeforces.com/blog/entry/48417
https://codeforces.com/blog/entry/44351
https://codeforces.com/blog/entry/48417
https://codeforces.com/blog/entry/10696
https://codeforces.com/blog/entry/57425
https://stackoverflow.com/questions/7089494/merge-multiple-sets-elements-in-a-single-set
https://www.spoj.com/problems/DQUERY/
https://codeforces.com/blog/entry/61203
https://codeforces.com/blog/entry/20032
https://codeforces.com/blog/entry/64236
https://codeforces.com/blog/entry/43230
https://codeforces.com/blog/entry/7383
https://codeforces.com/favourite/blogEntries
https://codeforces.com/blog/entry/8962
https://www.quora.com/What-is-an-approach-to-solve-the-problem-DQUERY-of-SPOJ-using-BIT-Segment-Tree
https://discuss.codechef.com/t/spoj-dquery-tle-with-mos-algorithm/12247
https://discuss.codechef.com/t/spoj-dquery-tle-with-mos-algorithm/12247
https://www.youtube.com/watch?v=hqaRYgsLpUI
http://www.codebytes.in/2017/07/spojdquery-solution-sortsegment-tree-c.html
https://yuting-zhang.github.io/spoj/2017/01/29/SPOJ-DQUERY.html
https://stackoverflow.com/questions/18553567/difficulty-in-understanding-the-approach-for-solving-spoj-dquery
https://codeforces.com/blog/entry/43230
https://codeforces.com/blog/entry/64236
https://codeforces.com/blog/entry/20032
https://codeforces.com/blog/entry/20032
https://codeforces.com/blog/entry/20032
https://codeforces.com/blog/entry/61203
https://codeforces.com/blog/entry/22284
https://codeforces.com/blog/entry/68271
https://codeforces.com/blog/entry/44711
https://codeforces.com/blog/entry/65037
https://codeforces.com/blog/entry/50353
https://codeforces.com/blog/entry/69219
https://codeforces.com/blog/entry/63327
https://codeforces.com/topic/69697/en1
https://codeforces.com/blog/entry/52460
https://codeforces.com/blog/entry/52062
https://codeforces.com/blog/entry/52062
https://codeforces.com/blog/entry/69775
https://codeforces.com/blog/entry/10493
https://codeforces.com/blog/entry/9204
https://www.spoj.com/problems/MKTHNUM/



