https://codeforces.com/contest/852/problem/I
https://www.spoj.com/problems/QTREE/
https://www.spoj.com/problems/DQUERY/
https://www.quora.com/How-to-solve-Wealth-Disparity-from-INOI-2016
https://codeforces.com/problemset/problem/375/D
https://courses.csail.mit.edu/6.851/spring12/scribe/L20.pdf
https://codeforces.com/blog/entry/22060
https://www.spoj.com/problems/COT2/
https://codeforces.com/gym/100962/attachments/download/4255/20152016-petrozavodsk-winter-training-camp-moscow-su-trinity-contest-en.pdf
https://www.codechef.com/ALKH2016/problems/VLB
https://discuss.codechef.com/t/mlchef-editorial/3172

http://cfrp.azurewebsites.net/blog/entry/62456
https://codeforces.com/blog/entry/68271
https://codeforces.com/blog/entry/50353
https://codeforces.com/blog/entry/55574
https://codeforces.com/blog/entry/7383
https://codeforces.com/blog/entry/20032
https://codeforces.com/blog/entry/44711
https://codeforces.com/blog/entry/15890
https://www.geeksforgeeks.org/mos-algorithm-query-square-root-decomposition-set-1-introduction/
https://cp-algorithms.com/data_structures/sqrt_decomposition.html
http://hmrockstar.blogspot.com/2017/07/mos-query-sqrt-decomposition-algorithm.html
https://www.hackerearth.com/practice/notes/mos-algorithm/
https://discuss.codechef.com/t/merge-sort-tree-tutorial/14277
https://github.com/Errichto/youtube/wiki/Video-ideas
